#!/bin/bash
yum install -y httpd
sudo yum install ruby
sudo yum install ruby
cd /home/ec2-user
sudo wget https://aws-codedeploy-eu-west-2.s3.eu-west-2.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto
sudo service codedeploy-agent start
